---
title: "Untitled"
format: html
editor: visual
---

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
# Create a leaflet map to plot all earthquakes using circles with name of the locatio and pops up

# Assuming you have already read the dataset into R
earthquake_data <- read.csv("C:\\Users\\Venkata\\Desktop\\stat1\\Homework2\\Japan_earthquakes.csv")

# Create a subset of earthquakes with magnitude 6 or higher
high_magnitude_earthquakes <- earthquake_data %>%
  filter(mag >= 6)
 leaflet(high_magnitude_earthquakes) %>%
  addProviderTiles(providers$Esri.WorldStreetMap) %>%  # Use CartoDB tiles for an elegant base map
  setView(lng = 138.2529, lat = 36.2048, zoom = 5) %>%  # Center the map around Japan
  addCircles(
    lng = ~longitude, lat = ~latitude, 
    radius = ~sqrt(10^mag) * 4,  # Scaling the circle radius based on earthquake magnitude
    color = "#FF5733",  # Aesthetic border color (orange-red)
    fillColor = "yellow",  # Fill color (lighter yellow-orange)
    fillOpacity = 0.6,
    label = ~place,  # Add labels for each circle indicating the earthquake location
     popup = "Test Popup"
  ) 
```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
